project:
  type: website

website:
  title: "Zulhakar"
  navbar:
    left:
      - index.qmd
      - about.qmd
    right:
      - href: https://zulhakar.github.io/OnlyBlends.Mixer.Docs/
        text: Onlyblends.Mixer
      - icon: youtube
        href: https://www.youtube.com/@Zulhakar
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
     
    #theme:
    #  - cosmo
    #  - brand
