project:
  type: website

website:
  title: "Zulhakar"
  draft-mode: unlinked
  
  navbar:
    title: false 
    left:
      - index.qmd
      - projects.qmd
    right:
      - href: https://extensions.blender.org/author/41884/
        text: "![Onlyblends.Mixer](https://download.blender.org/branding/community/blender_community_badge_black.svg){height=1.6em}"
      - icon: youtube
        href: https://www.youtube.com/@Zulhakar
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: sketchy
      dark: vapor
     
    #theme:
    #  - cosmo
    #  - brand
